---
services:
  pst:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pst_files:/app/pst_files
      - ./output_emails:/app/output_emails
    stdin_open: true
    tty: true
